#!/usr/bin/env php
<?php
// $Id$

/**
 * @file xsvn-pre-commit.php
 *
 * Provides a path-based commit access restriction to the branches/live
 * directory. Expects to be provided an authfile of the form generated by the
 * export_users_dbm module.
 */

function xsvn_get_commit_author($txn, $repo) {
  return shell_exec("svnlook author -t $txn $repo");
}

function xsvn_get_commit_parent_dir($txn, $repo) {
  return shell_exec("svnlook dirs-changed -t $txn $repo");
}

function xsvn_is_maintainer($id, $name, $project) {
  $record = dba_fetch($name, $id);
  $roles = substr($record, strrpos($record, ':') + 1);
  $roles = str_replace('svn-', '', explode(',', $roles));
  return array_search("$project-maintainer", $roles) !== FALSE;
}

function xsvn_check_commit($argv) {
  // Don't need the script name, shift it off the top.
  array_shift($argv);
  list($repo, $txn, $authfile, $project) = $argv;
  // Check to see if the restricted directory is being accessed before bothering
  // to open up the auth file.
  if (!preg_match('@^branches\/live@i', xsvn_get_commit_parent_dir($txn, $repo))) {
    exit(0);
  }
  // Commit is pointed to the restricted branch, so check the auth file.
  $id = dba_open($authfile, 'r');
  $access = xsvn_is_maintainer($id, xsvn_get_commit_author($txn, $repo), $project);
  dba_close($id);
  $access ? exit(0) : exit(1);
}

xsvn_check_commit($argv);